name: workshop-202609 # Name needs to be changed in .github/workflows/update-pinned-env.yaml too
channels:
- conda-forge
dependencies:
- python>=3.13,<3.14
- pip

  # main packages
- numpy
- scipy
- pandas>=2,<3
- geopandas>=1
- xarray
- netcdf4
- pyarrow
- numba

  # interactive python
- ipython
- jupyterlab

  # reading particular file types
- lxml
- openpyxl

  # geodata utilities
- shapely>2
- cartopy>=0.22

  # plotting
- matplotlib>=3.9
- plotly<6

  # development tools
- pre-commit

- pip:
  - highspy>=1.5.3
  - pypsa[excel]>=1.1
  - jupyter-book>=2
